# Generated by Django 5.0.3 on 2024-03-14 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('base_rate', models.PositiveIntegerField(default=0, verbose_name='Ставка за выход')),
                ('included_deliveries', models.PositiveIntegerField(default=0, verbose_name='Кол-во включенных доставок')),
                ('rate_for_delivery', models.PositiveIntegerField(default=0, verbose_name='Ставка за доставку')),
            ],
        ),
        migrations.AlterField(
            model_name='courier',
            name='phone',
            field=models.PositiveBigIntegerField(verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='courier',
            name='motivation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier', to='couriers.motivation', verbose_name='Мотивация'),
        ),
    ]
