# Generated by Django 5.0.3 on 2024-03-22 12:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierСard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date, verbose_name='Дата карты')),
                ('count_deliveries', models.IntegerField(default=0, verbose_name='Количество доставок')),
            ],
        ),
        migrations.CreateModel(
            name='Motivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('base_rate', models.PositiveIntegerField(default=0, verbose_name='Ставка за выход')),
                ('included_deliveries', models.PositiveIntegerField(default=0, verbose_name='Кол-во включенных доставок')),
                ('rate_for_delivery', models.PositiveIntegerField(default=0, verbose_name='Ставка за доставку')),
            ],
        ),
        migrations.AlterField(
            model_name='courier',
            name='phone',
            field=models.PositiveBigIntegerField(verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='courier',
            name='courier_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couriercard', to='couriers.courierсard', verbose_name='Курьерские карты'),
        ),
        migrations.AddField(
            model_name='courier',
            name='motivation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier', to='couriers.motivation', verbose_name='Мотивация'),
        ),
    ]
