# Generated by Django 5.0.3 on 2024-03-14 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0002_motivation_alter_courier_phone_courier_motivation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierСard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата карты')),
                ('count_deliveries', models.IntegerField(default=0, verbose_name='Количество доставок')),
            ],
        ),
        migrations.AlterField(
            model_name='motivation',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='courier',
            name='courier_cards',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_card', to='couriers.courierсard', verbose_name='Курьерская карта'),
        ),
    ]
