# Generated by Django 5.0.3 on 2024-03-14 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0003_courierсard_alter_motivation_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierсard',
            name='date',
            field=models.DateField(default=datetime.date, verbose_name='Дата карты'),
        ),
    ]
