# Generated by Django 5.0.3 on 2024-03-14 19:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0004_alter_courierсard_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='courier_cards',
        ),
        migrations.AddField(
            model_name='courierсard',
            name='courier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier', to='couriers.courier', verbose_name='Курьер'),
        ),
        migrations.AlterField(
            model_name='courierсard',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 14), verbose_name='Дата карты'),
        ),
    ]
